### ISSUE TITLE
Rework Dockerfile to make it work

### ISSUE THREAD

**Issue by LetUsFlow** [Giftzwerg02/oxo#8]
I will rework this once Rust 1.68 ist stable.
Or maybe @a-nick-fischer will do it, but he doesn't know yet.

**Comment by LetUsFlow** [comment]
Note: load yt-dlp directly from `https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp` instead of from a docker image
this is a "platform-independent [zipimport](https://docs.python.org/3/library/zipimport.html) binary", containing fancy magic

**Comment by LetUsFlow** [comment]
> this is a "platform-independent [zipimport](https://docs.python.org/3/library/zipimport.html) binary", containing fancy magic
it doesn't actually contain magic, it just contains a zip file

**Comment by a-nick-fischer** [comment]
But does the zip file contain magic? ;)

**Comment by LetUsFlow** [comment]
no, it contains zip!
isn't that obvious? :D

**Comment by LetUsFlow** [comment]
This issue should be closed with commit d23b2dd, but it is still untested

**Comment by LetUsFlow** [comment]
This should be finished with commit d23b2dd, but it still needs testing

**Comment by LetUsFlow** [comment]
This is now finished with 170eaa0
I can confirm it works as expected
